name: Deploy Worker to Cloudflare

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Publish to Cloudflare Workers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Deploy to Cloudflare
        run: |
          wrangler deploy
